<a href="https://colab.research.google.com/github/sath-27/Beginner-practice/blob/main/Classification_algorithms_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Importing dataset

In [ ]:
data = pd.read_csv('Social_Network_Ads.csv')
X = data.iloc[: , :-1].values
Y = data.iloc[: , -1].values

Splitting data into train and test

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state = 69) 

In [ ]:
print(X_train)

[[    31  74000]
 [    34  25000]
 [    52 114000]
 [    35 108000]
 [    18  86000]
 [    39  59000]
 [    40 107000]
 [    27  96000]
 [    47  30000]
 [    30 116000]
 [    49  28000]
 [    52 150000]
 [    25  80000]
 [    37  78000]
 [    30  62000]
 [    48 138000]
 [    35  50000]
 [    20  23000]
 [    26  15000]
 [    25  79000]
 [    44 139000]
 [    38 112000]
 [    30  80000]
 [    42  54000]
 [    48  96000]
 [    26  72000]
 [    39 106000]
 [    30  89000]
 [    19  85000]
 [    54 104000]
 [    49 141000]
 [    35  60000]
 [    38  61000]
 [    26  15000]
 [    48  35000]
 [    60  46000]
 [    42  54000]
 [    35  39000]
 [    46 117000]
 [    32 100000]
 [    24  19000]
 [    30 135000]
 [    20  82000]
 [    56  60000]
 [    40  78000]
 [    54  26000]
 [    39  42000]
 [    40  57000]
 [    60 102000]
 [    55 125000]
 [    28  44000]
 [    40  75000]
 [    35  88000]
 [    18  82000]
 [    29  43000]
 [    37  80000]
 [    33  28000]
 [    38  61000]
 [    39  7500

In [ ]:
print(X_test)

[[    46  22000]
 [    37  62000]
 [    48 141000]
 [    25  87000]
 [    47  50000]
 [    21  72000]
 [    48  33000]
 [    46  28000]
 [    38  51000]
 [    32 150000]
 [    35  25000]
 [    35  61000]
 [    26  43000]
 [    59  29000]
 [    46  82000]
 [    32  18000]
 [    22  18000]
 [    40  71000]
 [    45  45000]
 [    37  79000]
 [    27 137000]
 [    42 108000]
 [    28  59000]
 [    21  68000]
 [    36 126000]
 [    59 143000]
 [    28  79000]
 [    38  50000]
 [    58 101000]
 [    58  23000]
 [    35  44000]
 [    31  58000]
 [    26  80000]
 [    47  47000]
 [    39  79000]
 [    37 144000]
 [    26  52000]
 [    52  90000]
 [    26 118000]
 [    32 117000]
 [    22  27000]
 [    35  47000]
 [    22  55000]
 [    35 147000]
 [    49  74000]
 [    50  88000]
 [    41  51000]
 [    53  82000]
 [    27  57000]
 [    45  26000]
 [    51 146000]
 [    47  20000]
 [    39  96000]
 [    47  34000]
 [    29  80000]
 [    27  58000]
 [    40  57000]
 [    19  25000]
 [    20  8600

In [ ]:
print(Y_train)

[0 0 0 0 0 0 1 1 1 0 1 1 0 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 1 1 0
 0 1 1 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 1 0 1 1 0 0 0 0 0
 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 1 1 0 0 1 0 1 0 1 0 0 0
 1 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0
 0 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 1 0 0
 1 1 1 0 1 0 0 0 1 1 0 0 1 0 1 1 1 1 1 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 1
 0 0 1 1 1 0 0 1 0 1 0 1 1 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0
 0 0 0 0]


In [ ]:
print(Y_test)

[0 0 0 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0
 1 0 1 0 0 0 1 0 1 0 1 0 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 1
 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0]


Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-0.66866643  0.13575231]
 [-0.37610455 -1.31767734]
 [ 1.37926674  1.32222549]
 [-0.27858393  1.14425451]
 [-1.93643459  0.49169426]
 [ 0.11149858 -0.30917514]
 [ 0.20901921  1.11459268]
 [-1.05874894  0.78831255]
 [ 0.8916636  -1.16936819]
 [-0.76618706  1.38154914]
 [ 1.08670486 -1.22869185]
 [ 1.37926674  2.39005135]
 [-1.2537902   0.31372328]
 [-0.08354267  0.25439962]
 [-0.76618706 -0.22018965]
 [ 0.98918423  2.03410939]
 [-0.27858393 -0.5761316 ]
 [-1.74139333 -1.377001  ]
 [-1.15626957 -1.61429563]
 [-1.2537902   0.28406145]
 [ 0.59910172  2.06377122]
 [ 0.01397796  1.26290183]
 [-0.76618706  0.31372328]
 [ 0.40406047 -0.45748428]
 [ 0.98918423  0.78831255]
 [-1.15626957  0.07642865]
 [ 0.11149858  1.08493085]
 [-0.76618706  0.58067975]
 [-1.83891396  0.46203243]
 [ 1.57430799  1.02560719]
 [ 1.08670486  2.12309488]
 [-0.27858393 -0.27951331]
 [ 0.01397796 -0.24985148]
 [-1.15626957 -1.61429563]
 [ 0.98918423 -1.02105904]
 [ 2.15943176 -0.69477892]
 [ 0.40406047 -0.45748428]
 

In [ ]:
print(X_test)

[[ 0.79414297 -1.40666283]
 [-0.08354267 -0.22018965]
 [ 0.98918423  2.12309488]
 [-1.2537902   0.52135609]
 [ 0.8916636  -0.5761316 ]
 [-1.64387271  0.07642865]
 [ 0.98918423 -1.0803827 ]
 [ 0.79414297 -1.22869185]
 [ 0.01397796 -0.54646977]
 [-0.57114581  2.39005135]
 [-0.27858393 -1.31767734]
 [-0.27858393 -0.24985148]
 [-1.15626957 -0.78376441]
 [ 2.06191113 -1.19903002]
 [ 0.79414297  0.37304694]
 [-0.57114581 -1.52531014]
 [-1.54635208 -1.52531014]
 [ 0.20901921  0.04676682]
 [ 0.69662235 -0.72444075]
 [-0.08354267  0.28406145]
 [-1.05874894  2.00444756]
 [ 0.40406047  1.14425451]
 [-0.96122832 -0.30917514]
 [-1.64387271 -0.04221867]
 [-0.1810633   1.67816744]
 [ 2.06191113  2.18241854]
 [-0.96122832  0.28406145]
 [ 0.01397796 -0.5761316 ]
 [ 1.9643905   0.9366217 ]
 [ 1.9643905  -1.377001  ]
 [-0.27858393 -0.75410258]
 [-0.66866643 -0.33883697]
 [-1.15626957  0.31372328]
 [ 0.8916636  -0.66511709]
 [ 0.11149858  0.28406145]
 [-0.08354267  2.21208037]
 [-1.15626957 -0.51680794]
 

Training Logistic Regression Model on training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=69)
classifier.fit(X_train , Y_train)

LogisticRegression(random_state=69)

Predicting New Result

In [ ]:
print(classifier.predict(sc.transform([[30, 87000]])))

[0]


Predicting the test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), Y_test.reshape(len(Y_test), 1)), 1)) 

[[0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]]


Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test , y_pred)
print (cm)
print(accuracy_score(Y_test, y_pred))


[[57  5]
 [13 25]]
0.82


Training KNN Model on training set

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier1 = KNeighborsClassifier(n_neighbors = 5 , metric = 'minkowski' , p=2)
classifier1.fit(X_train, Y_train)

KNeighborsClassifier()

Predicting New result

In [ ]:
print(classifier1.predict(sc.transform([[30, 87000]])))

[0]


Predicting the test set results

In [ ]:
y_pred1 = classifier1.predict(X_test)
print(np.concatenate((y_pred1.reshape(len(y_pred1), 1), Y_test.reshape(len(Y_test), 1)), 1)) 

[[1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(Y_test , y_pred1)
print(cm)
print(accuracy_score(Y_test , y_pred1))

[[55  7]
 [ 5 33]]
0.88


Training SVM on the training data

In [ ]:
from sklearn.svm import SVC
classifier2 = SVC(kernel = 'linear' , random_state = 0)
classifier2.fit(X_train, Y_train)

SVC(kernel='linear', random_state=0)

Predicting new result

In [ ]:
print(classifier2.predict(sc.transform([[30, 87000]])))

[0]


Predicting the test set results

In [ ]:
y_pred2 = classifier2.predict(X_test)
print(np.concatenate((y_pred1.reshape(len(y_pred1), 1), Y_test.reshape(len(Y_test), 1)), 1))


[[1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]]


Training Decision tree classifier on training data

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier3 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier3.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

Predicting new result

In [ ]:
print(classifier3.predict(sc.transform([[30,87000]])))

[0]


Predicting test set results

In [ ]:
y_pred3 = classifier3.predict(X_test)
print(y_pred3)

[1 0 1 0 1 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0
 1 1 0 0 0 0 1 1 1 0 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 0 0 1
 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 1 0 1 0]


In [ ]:
print(np.concatenate((y_pred3.reshape(len(y_pred3), 1), Y_test.reshape(len(Y_test), 1)) , 1))

[[1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(Y_test, y_pred3))
print(accuracy_score(Y_test, y_pred3))

[[55  7]
 [ 7 31]]
0.86
